version: "3.7"
services:
  plex:
    build:
      context: ${PWD}/docker/plex
      dockerfile: ${PWD}/docker/plex/Dockerfile
    container_name: plex
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_API_KEY}
    volumes:
      - plexlibrary:/config
      - movies:/movies
      - music:/music
      - downloadsmusic:/music/downloads
      - downloadsvideo:/movies/downloads
      - plextranscode:/transcode
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
      - "50001:50001"
      - "50002:50002"
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    depends_on:
      - xteve
    logging: &glog
      driver: json-file
      options: 
        tag: "{{.ImageName}}/{{.Name}}"
        max-size: "10Mb"
  www:
    build:
      context: ${PWD}/docker/nginx
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    ports:
      - 80:${NGINX_PORT}
      - 443:${NGINX_SSL_PORT}
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
       - ${PWD}/docker/nginx/templates:/etc/nginx/templates
       - tmp:/tmp
       - log:/log/nginx/
       - nextclouddata:/fs/storage
       - nextcloud:/var/www/nextcloud
       - nextcloudconfig:/var/www/nextcloud/config
       - wwwdata:/var/www/public
       - certbot:/var/www/certbot/:ro
       - certbotconfig:/etc/nginx/ssl/:ro
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
       - calibre-web
       - nextcloud
       - php
       - plex
       - hlsproxy
       - xteve
       - transmissionbt
    logging: *glog
  certbot:
    image: certbot/certbot:v1.30.0
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - certbot:/var/www/certbot/:rw
      - certbotconfig:/etc/letsencrypt/:rw
      - log:/var/log/letsencrypt/
    env_file:
      - .env
    restart: "no"
    entrypoint:
      /usr/local/bin/certbot certonly --webroot -v --webroot-path /var/www/certbot/ --config-dir /var/www/certbot/config --logs-dir /var/log/letsencrypt/ --work-dir /var/www/certbot/work -d "${NGINX_HOST}"
    logging: *glog
  php:
    build:
      context: ${PWD}/docker/php
      dockerfile: ${PWD}/docker/php/Dockerfile
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - sock:/sock
      - tmp:/tmp
      - wwwdata:/var/www/public
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
  nextcloud:
    build:
      context: ${PWD}/docker/nextcloud
      dockerfile: ${PWD}/docker/nextcloud/Dockerfile
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/fs/storage
    volumes:
      - nextclouddata:/fs/storage
      - nextcloud:/var/www/nextcloud
      - nextcloudconfig:/var/www/nextcloud/config
    links:
      - mariadb
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped
    logging: *glog
  calibre-web:
    build:
      context: ${PWD}/docker/calibre
      dockerfile: ${PWD}/docker/calibre/Dockerfile
    container_name: calibre-web
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - calibrelibrary:/config
      - books:/books
      - tmp:/tmp
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
  mariadb:
    build:
      context: ${PWD}/docker/mariadb
      dockerfile: ${PWD}/docker/mariadb/Dockerfile
    container_name: mariadb
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - mariadb:/var/lib/mysql
      - mariadbinit:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
  hlsproxy:
    build:
      context: ${PWD}/docker/hlsproxy
      dockerfile: ${PWD}/docker/hlsproxy/Dockerfile
      args:
        - PORT=${HLSPROXY_PORT}
    container_name: hlsproxy
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - hlsproxycache:/data
      - ${PWD}/docker/hlsproxy/local.json:/opt/hlsp/local.json
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
  xteve:
    build:
      context: ${PWD}/docker/xteve
      dockerfile: ${PWD}/docker/xteve/Dockerfile
      args:
        - PORT=${XTEVE_PORT}
    container_name: xteve
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - xtevedata:/xteve
      - ${PWD}/docker/xteve/settings.json:/xteve/settings.json
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    depends_on:
      - hlsproxy
    restart: unless-stopped
    logging: *glog
  transmissionbt:
    build:
      context: ${PWD}/docker/transmission
      dockerfile: ${PWD}/docker/transmission/Dockerfile
    container_name: transmission
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - USER=${TRANS_USER}
      - PASS=${TRANS_PASSWORD}
    volumes:
      - transmissiondata:/config
      - downloads:/downloads
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
  proftp:
    build:
      context: ${PWD}/docker/proftpd
      dockerfile: ${PWD}/docker/proftpd/Dockerfile
      args:
        - PASSIVE_PORT_MIN=${PASSIVE_PORT_MIN}
        - PASSIVE_PORT_MAX=${PASSIVE_PORT_MAX}
        - PROFTPD_DATA_PORT=${PROFTPD_DATA_PORT}
        - PROFTPD_CTRL_PORT=${PROFTPD_CTRL_PORT}
    container_name: proftp
    environment:
      - USER_GID=${CUSTOM_GID}
      - PROFTPDHOST="ftp.${NGINX_HOST}"
    volumes:
      - downloads:/opt/ftp
      - ftpuser1:/home/user1
      - ftpuser2:/home/user2
    ports:
      - ${PROFTPD_DATA_PORT}:${PROFTPD_DATA_PORT}
      - ${PROFTPD_CTRL_PORT}:${PROFTPD_CTRL_PORT}
      - ${PASSIVE_PORT_MIN}-${PASSIVE_PORT_MAX}:${PASSIVE_PORT_MIN}-${PASSIVE_PORT_MAX}
    env_file:
      - .env
    restart: unless-stopped
    logging: *glog
volumes:
  plexlibrary:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/plexlibrary"
  plextranscode:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/plextranscode"
  calibrelibrary:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/calibrelibrary"    
  movies:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/movies"
  music:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/music"
  books:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/books"
  downloads:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/downloads"
  downloadsmusic:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/downloads/Music"
  downloadsvideo:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/downloads/Video"
  tmp:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/tmp"
  backend:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/www"
  sock:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/sock"
  mariadb:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/db"
  mariadbinit:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/docker/mariadb/init"
  log: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/log"
  nextclouddata: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/nextcloud"
  wwwdata: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/www"
  certbot:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/certbot"
  certbotconfig:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/certbotconfig"
  nextcloud:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/nextcloud"
  nextcloudconfig: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/nextcloudconfig"
  transmissiondata:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/transmission"
  hlsproxycache: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/hlsproxy"
  xtevedata: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/xteve"
  ftpuser1: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/ftp/user1"
  ftpuser2: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/ftp/user2"