---
version: "2"
services:
  plex:
    build:
      context: .
      dockerfile: ${PWD}/docker/plex/Dockerfile
    container_name: plex
    #network_mode: host
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_API_KEY}
    volumes:
      - plexlibrary:/config
      - movies:/movies
#    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
  www:
    build:
      context: .
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    ports:
      - "80:8090"
      - "443:443"
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
       - ${PWD}/docker/nginx/default.conf.nginx:/etc/nginx/conf.d/default.conf
       - tmp:/tmp
       - log:/log/nginx/
       - nextclouddata:/fs/storage
       - nextcloud:/var/www/html
       - nextcloudconfig:/var/www/html/config
    env_file:
      - .env
    depends_on:
       - calibre-web
#       - nextcloud
#       - php
#       - plex
  php:
    image: php:7.4.13-fpm-alpine3.12
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    volumes:
      - sock:/sock
      - ${PWD}/docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${PWD}/docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - tmp:/tmp
    env_file:
      - .env
  nextcloud:
    build:
      context: .
      dockerfile: ${PWD}/docker/nextcloud/Dockerfile
    image: nextcloud:23.0.2-fpm-alpine
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/fs/storage
    volumes:
      - nextclouddata:/fs/storage
      - nextcloud:/var/www/html
      - nextcloudconfig:/var/www/html/config
    links:
      - mariadb
    env_file:
      - .env
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:version-0.6.16
    container_name: calibre-web
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - calibrelibrary:/config
      - books:/books
      - tmp:/tmp
    env_file:
      - .env
#    restart: unless-stopped
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
#    restart: unless-stopped
  transmissionbt:
    image: lscr.io/linuxserver/transmission:version-3.00-r5
    container_name: transmission
    environment:
      - PUID=${CUSTOM_UID}
      - PGID=${CUSTOM_GID}
      - TZ=${TZ}
      - USER=${TRANS_USER}
      - PASS=${TRANS_PASSWORD}
      - TRANSMISSION_WEB_HOME=/kettu/
    volumes:
      - transmissiondata:/config
      - downloads:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    env_file:
      - .env
#    restart: unless-stopped
volumes:
  plexlibrary:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/plexlibrary"
  calibrelibrary:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/calibrelibrary"    
  movies:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/movies"
  books:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/books"
  downloads: 
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/downloads"
  tmp:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/tmp"
  backend:
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/www"
  sock:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/docker/sock"
  mariadb:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/db"
  log: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/log"
  nextclouddata: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/fs/nextcloud"
  nextcloud: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/nextcloud"
  nextcloudconfig: 
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/nextcloudconfig"
  transmissiondata:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${PWD}/system/transmission"
